{
 "title": "Trunk-recorder",
 "description": "https://github.com/USA-RedDragon/trunk-recorder-prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "service", "label": "Service", "query": { "query": "label_values(service)" } },
   {
    "name": "system",
    "label": "System",
    "query": {
     "query": "label_values(trunk_recorder_active_calls,system)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top 5 Talkgroups",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, rate(trunk_recorder_calls{service=\"$service\",call_system=\"$system\"}[${__range_s}s]))",
     "legendFormat": "{{talkgroup}}"
    }
   ]
  },
  {
   "title": "Spike and Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(system) (rate(trunk_recorder_call_spike_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "Spikes"
    },
    {
     "expr": "sum by(system) (rate(trunk_recorder_call_error_count{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "Call Errors"
    },
    {
     "expr": "trunk_recorder_source_error_count{service=\"$service\"}",
     "legendFormat": "Source Errors"
    }
   ]
  },
  {
   "title": "Call Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(system) (rate(trunk_recorder_call_duration{system=\"$system\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recorders Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(service) (trunk_recorder_source_analog_recorders{service=\"$service\"})",
     "legendFormat": "Analog"
    },
    {
     "expr": "sum by(service) (trunk_recorder_source_digital_recorders{service=\"$service\"})",
     "legendFormat": "Digital"
    }
   ]
  },
  {
   "title": "Active Calls by System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(system) (trunk_recorder_active_calls{service=\"$service\", system=\"$system\"})",
     "legendFormat": "{{system}}"
    },
    {
     "expr": "sum(trunk_recorder_active_calls{service=\"$service\"})",
     "legendFormat": "All Systems"
    }
   ]
  },
  {
   "title": "Decoded Message Rate per System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(system) (rate(trunk_recorder_message_decodes{service=\"$service\", system=\"$system\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics Scrapes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(exposer_scrapes_total{service=\"$service\"}[$__rate_interval])",
     "legendFormat": "scrapes"
    }
   ]
  },
  {
   "title": "Percentage Encrypted Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(trunk_recorder_calls{service=\"$service\", encrypted=\"1\"}[$__rate_interval]))/sum(rate(trunk_recorder_calls{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "encrypted"
    },
    {
     "expr": "sum(rate(trunk_recorder_calls{service=\"$service\",encrypted=\"0\"}[$__rate_interval]))/sum(rate(trunk_recorder_calls{encrypted=\"0\",service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(exposer_transferred_bytes_total{service=\"$service\"}[$__rate_interval])",
     "legendFormat": "Transfer"
    }
   ]
  },
  {
   "title": "Metrics Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "exposer_request_latencies{service=\"$service\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "rate(exposer_request_latencies_sum{service=\"$service\"}[$__rate_interval]) / rate(exposer_request_latencies_count{service=\"$service\"}[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}