name: Docker

on:
  pull_request:
  push:
    branches: ['main']
    tags: ['v*']

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  docker:
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/docker-ci.yaml@d65722ccb9ea7d4e4b770754a67aecc037033f1b # v2.0.21
    with:
      push: ${{ github.event_name != 'pull_request' }}
